#!/usr/bin/env python3

import os
from subprocess import Popen, PIPE
import argparse

os.chdir(os.path.dirname(os.path.realpath(__file__)))
MAX = "10"  # out of 100

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--force", action="store_true")
arguments = parser.parse_args()

for root, dirs, files in os.walk("../photography/"):
    for name in files:
        # use jpegoptim to optimize raw images
        if name.endswith(("jpg", "jpeg")) and "raw" in root:
            path = os.path.join(root, name)

            # first command is to create a low-res version of the default image
            # second command is to strip the metadata from the pictures
            commands = [
                ["jpegoptim", "-s", f"-m{MAX}", path, "-d", os.path.join(root, "..")],
                ["jpegoptim", "-s", path],
            ]

            if arguments.force:
                commands[0].append("-o")

            for command in commands:
                result = (
                    [
                        f
                        for f in Popen(command, stdout=PIPE, stderr=PIPE).communicate()
                        if f != b""
                    ][0]
                    .decode()
                    .strip()
                )

                print(f"            Images: {result}")
